dataset: customer_7day_summary
grain: one_row_per_customer



numerical_features:
  - quantity
  - line_net_amount
  - total_items
  - total_cost
  - discount_applied

categorical_features:


  - loyalty_status

  - payment_method



dtypes:

  quantity: float
  line_net_amount: float
  total_items: float
  total_cost: float


  loyalty_status: string

  product_name: string
  payment_method: string
  discount_applied: boolean


constraints:
  quantity:
    min: 0
  line_net_amount:
    min: 0
  total_items:
    min: 0
  total_cost:
    min: 0
